project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Sabina Pedrazzini"
  #favicon: images/flower.png
  #navbar = on top of the page
  navbar:
    #logo: images/flower.png
    left:
      - href: CV/CV_index.qmd  
        text: "CV"
        
     # - href: mywork/index.qmd
      #  text: "My work"
    
    right:
      - icon: linkedin
        href: https://ch.linkedin.com/in/sabina-pedrazzini-543051169
      - icon: envelope
        href: "mailto:sabina.pedrazzini@gmail.com"


  page-footer: 
    left: |
      <span class="faux-block">&#169; 2025 Sabina Pedrazzini CC BY-SA 4.0</span>

format:
  html:
    theme: style_website.scss